### ISSUE TITLE
Fatal Error: control.lua:96

### ISSUE THREAD

**Issue by cdcrothers** [Sil3ntStorm/logistic-signals#2]
fatal error. mid-gameplay.
Stack trace and currently enabled & installed mods provided.
![image](https://user-images.githubusercontent.com/16570564/108613132-1ac40800-73bd-11eb-8289-e691fff7301e.png)
![image](https://user-images.githubusercontent.com/16570564/108613148-434c0200-73bd-11eb-8476-ec0ba398e72e.png)
![image](https://user-images.githubusercontent.com/16570564/108613149-43e49880-73bd-11eb-9605-0fc49381e486.png)
![image](https://user-images.githubusercontent.com/16570564/108613150-4515c580-73bd-11eb-9322-59dd80061894.png)
![image](https://user-images.githubusercontent.com/16570564/108613151-45ae5c00-73bd-11eb-8f39-9c65afc1b021.png)

**Comment by cdcrothers** [comment]
I modified the mod directly to basically patch in a "try catch" equivalent (which lua doesn't have... so i used pcall... lame) to prevent it from crashing my game.
![image](https://user-images.githubusercontent.com/16570564/108613562-26b1c900-73c1-11eb-9f3e-cdc6785a5353.png)
I have no idea how to write lua tho, so that simple change took me like 20 min  to figure out, and resulted in the mod simply not working anymore.

You may be more easily able to identify the root cause or apply a more proper fix.

This issue started the same day the follow mods were installed:
BlueprintSignals_0.3.0
creative-mod_1.7.2

**Comment by cdcrothers** [comment]
Unsure if it was those mods specifically or something else.
Uninstall and reinstall didn't fix. Tried first without those 2 new mods, then again after. 

Crash stopped after any reinstalls (despite not having my "fix"), but mod continued not to work after my fix was first applied.

**Comment by Sil3ntStorm** [comment]
Thanks for the report.
This happens when a single network has outstanding (not being fulfilled) requests totaling more than 2.14 billion for any one item (e.g. 500 chests each requesting 4.4 million coal).
Fixed and uploaded new version.

**Comment by cdcrothers** [comment]
@Sil3ntStorm impressive response time! 
Do you have a Patreon? I'd love to give back.
